name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obténdo o código
      uses: actions/checkout@v4.1.7
      with:
        context: ./src
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6.7.0
      with:
        context: ./src
        file: ./src/DockerFile
        push: true
        tags: | 
          pablomesq/php-rabbitmq:v${{ github.run_number }}
          pablomesq/php-rabbitmq:latest
